name: kernel_build
on:
  push
jobs:
  kernel:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defconfig: [defconfig, allyesconfig, allmodconfig, allnoconfig]

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install make gcc flex bison libelf-dev libssl-dev -y
      - name: build kernel
        run: make defconfig && make -j`nproc`
