name: kernel_build
on:
  push
jobs:
  kernel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt build-dep linux-generic -y
      - name: build kernel
        run: make defconfig && make -j`nproc`
